[build]
  command = "npm install --no-frozen-lockfile && npm run build"
  publish = "public"
  [build.environment]
    NETLIFY_USE_NPM = "true"

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  included_files = ["build/public/**"]

[[redirects]]
  from = "/_assets/*"
  to = "/build/_assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000" 